SELECT * FROM PF0645.CONDICOES_METEOROLOGICAS_MARTE;

--QUESTÃO 1
SELECT MES_MARTE, MIN(MIN_TEMP)MAIOR_DAS_MAIORES_TEMPERATURAS, MAX(MAX_TEMP)MENOR_DAS_MENORES_TEMPERATURAS
FROM PF0645.CONDICOES_METEOROLOGICAS_MARTE
WHERE PRESSAO_ATM > (SELECT AVG(PRESSAO_ATM) FROM PF0645.CONDICOES_METEOROLOGICAS_MARTE)
GROUP BY MES_MARTE
ORDER BY MES_MARTE;

--QUESTÃO 2
CREATE TABLE MED_ACIMA_PRESSAO_ATM
(ID NUMBER, PRESSAO_ATM_MED NUMBER);
CREATE TABLE MAX_TEMP_HIST_Q1
(ID NUMBER, MAX_TEMP NUMBER);
CREATE TABLE MAX_TEMP_HIST_Q2
(ID NUMBER, MAX_TEMP NUMBER);
CREATE TABLE MAX_TEMP_HIST_Q3 (
ID NUMBER, MAX_TEMP NUMBER);
CREATE TABLE MAX_TEMP_HIST_Q4
(ID NUMBER, MAX_TEMP NUMBER);

INSERT FIRST
  WHEN PRESSAO_ATM  > 839 THEN
    INTO MED_ACIMA_PRESSAO_ATM VALUES(ID, PRESSAO_ATM)
  WHEN EXTRACT(MONTH FROM data_terra) IN (1,2,3) THEN
    INTO MAX_TEMP_HIST_Q1 VALUES(ID, MAX_TEMP)
  WHEN EXTRACT(MONTH FROM data_terra) IN (4,5,6) THEN
    INTO MAX_TEMP_HIST_Q2 VALUES(ID, MAX_TEMP)
  WHEN EXTRACT(MONTH FROM data_terra) IN (7,8,9) THEN
    INTO MAX_TEMP_HIST_Q3 VALUES(ID, MAX_TEMP)
  WHEN EXTRACT(MONTH FROM data_terra) IN (10,11,12) THEN
    INTO MAX_TEMP_HIST_Q4 VALUES(ID, MAX_TEMP)
    
select count(*) "Total" from MED_ACIMA_PRESSAO_ATM;
select count(*) "Total" from MAX_TEMP_HIST_Q1;
select count(*) "Total" from MAX_TEMP_HIST_Q2;
select count(*) "Total" from MAX_TEMP_HIST_Q3;
select count(*) "Total" from MAX_TEMP_HIST_Q4;

--QUESTÃO 3
SELECT MES_MARTE,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 01' THEN min_temp ELSE NULL END),2) AS M01_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 01' THEN max_temp ELSE NULL END),2) AS M01_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 02' THEN min_temp ELSE NULL END),2) AS M02_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 02' THEN max_temp ELSE NULL END),2) AS M02_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 03' THEN min_temp ELSE NULL END),2) AS M03_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 03' THEN max_temp ELSE NULL END),2) AS M03_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 04' THEN min_temp ELSE NULL END),2) AS M04_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 04' THEN max_temp ELSE NULL END),2) AS M04_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 05' THEN min_temp ELSE NULL END),2) AS M05_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 05' THEN max_temp ELSE NULL END),2) AS M05_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 06' THEN min_temp ELSE NULL END),2) AS M06_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 06' THEN max_temp ELSE NULL END),2) AS M06_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 07' THEN min_temp ELSE NULL END),2) AS M07_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 07' THEN max_temp ELSE NULL END),2) AS M07_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 08' THEN min_temp ELSE NULL END),2) AS M08_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 08' THEN max_temp ELSE NULL END),2) AS M08_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 09' THEN min_temp ELSE NULL END),2) AS M09_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 09' THEN max_temp ELSE NULL END),2) AS M09_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 10' THEN min_temp ELSE NULL END),2) AS M10_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 10' THEN max_temp ELSE NULL END),2) AS M10_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 11' THEN min_temp ELSE NULL END),2) AS M11_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 11' THEN max_temp ELSE NULL END),2) AS M11_MED_Max,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 12' THEN min_temp ELSE NULL END),2) AS M12_MED_MIN,
    ROUND(AVG(CASE WHEN MES_MARTE = 'Mes 12' THEN max_temp ELSE NULL END),2) AS M12_MED_Max
FROM PF0645.CONDICOES_METEOROLOGICAS_MARTE
GROUP BY MES_MARTE
ORDER BY MES_MARTE;


